// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psiuubvmezlopmvghwpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaXV1YnZtZXpsb3Btdmdod3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjM2MTgsImV4cCI6MjA2NjUzOTYxOH0.w7dfBMJBxePhRVmCBOJyj-6eoxDYEJQOLoJi4cXozTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);